Use AES GCM for kernel encryption to ensure integrity
MarcusGrass/boot-rs pull request #2
Opened 2023-03-31 07:37 UTC by MarcusGrass

Encrypts kernel using AES GCM to ensure integrity of the decrypted payload.

Not a lot of meaningful changes outside of the IV/nonce going from 16 to 12 bytes, some drive-by clippy cleanups.

2023-03-31 15:58 UTC, eternal-flame-AD requested changes
Looks good except the nonce issue. I would definitely distinguish IV and nonce, it is renamed to nonce because it MUST be random for each encryption stream.

I also tried myself to build a misuse resilient and configurable crypto system [here](https://github.com/eternal-flame-AD/boot-rs/tree/c6d0fdfbce6210dab9297ee5d84ec9f214a538e5/boot-crypt), where all the user has to do is give a password , I generate a random salt internally and the instantiation with the IVs and nonces just happen. The salt is written to the file header so during decryption I can internally recover the IV/nonce and the user can just use the data using the `unseal` and then `decrypt` methods.

2023-03-31 15:58 UTC, eternal-flame-AD commented on boot-lib/src/crypt.rs
> +    let nonce = Nonce::from_slice(&iv);
Nonce should not come from a static config file, this is a footgun for the user bc if nonce is unchanged between encryptions [key recovery is possible](https://www.elttam.com/blog/key-recovery-attacks-on-gcm/). I used [GCM-SIV](https://docs.rs/aes-gcm-siv/latest/aes_gcm_siv/) mode is more resilient to these kinds of mistakes at a little cost of performance although the expectation from users is the same: nonce are what they mean they should be random

Take a look at my implementation, which hides the complexity of choosing IVs and nonces from the user.

[Here](https://github.com/eternal-flame-AD/boot-rs/blob/c6d0fdfbce6210dab9297ee5d84ec9f214a538e5/boot-crypt/src/algorithm.rs#L146), he encryption key and necessary IV/nonce is simply derived from one Argon2 KDF, I wrote a `fixed_iv` override just for backward compatibility. During encryption the salt is randomly [generated](https://github.com/eternal-flame-AD/boot-rs/blob/c6d0fdfbce6210dab9297ee5d84ec9f214a538e5/boot-crypt/src/parcel.rs#L38) and written into the blob [header](https://github.com/eternal-flame-AD/boot-rs/blob/c6d0fdfbce6210dab9297ee5d84ec9f214a538e5/boot-crypt/src/parcel.rs#L17), guaranteeing that IV and nonce never repeat. During decryption we just parse the header and use the same salt to recover the cipher state.

With this the user only have to do [this](https://github.com/eternal-flame-AD/boot-rs/blob/c6d0fdfbce6210dab9297ee5d84ec9f214a538e5/boot-crypt/src/lib.rs#L22) to encrypt and seal data, and the input is only plaintext and password.

2023-03-31 15:58 UTC, eternal-flame-AD commented on boot.cfg.tst
remove the IV and salt config from this file for reason above

2023-04-05 19:09 UTC, MarcusGrass commented
Sorry for the delay, it's bin a lot lately, now the encryption details are baked into the encrypted blob header!

2023-04-06 00:51 UTC, eternal-flame-AD reviewed
Looks good, dunno why you decided to keep the nonce out of the KDF, I would say a bit more complex than it has to be but okay. Just that one fat finger and good to go!

In the long run I suggest 
1. maybe refactor some bin programs, there are super long functions called thing like generate, gen_key_file which I find it a bit hard to read, at least use empty lines to give it some separation on what subtask you are doing.
1. would be cool to have some documentations on how to set this thing up from a regular LUKS encrypted install. Call me wrong if I what I am saying is impossible, I would think it would be easier if you don't take away the job of currently well-known facilities like mkinitcpio and just write hooks for that instead.

2023-04-06 00:51 UTC, eternal-flame-AD commented on Cargo.lock
> +git# This file is automatically @generated by Cargo.
What's happening here? 'D

2023-04-06 00:51 UTC, eternal-flame-AD commented on boot-strap/src/main.rs
> +    let enc_c = encrypted.clone();
You don't need to clone now

2023-04-06 00:51 UTC, eternal-flame-AD commented on boot-lib/src/crypt.rs
> +    fn serde_test() {
metadata_serialize_deserialize or metadata_serdes

2023-04-06 00:51 UTC, eternal-flame-AD commented on boot-strap/src/main.rs
> -fn generate_crypt_randoms() -> Result<([u8; 16], [u8; 32]), String> {
maybe rename this function?? It does much more than it says on the name

2023-04-06 07:24 UTC, MarcusGrass commented on Cargo.lock
> +git# This file is automatically @generated by Cargo.
I think this was a slip that somehow made it into the commit, it was overwritten locally so I didn't even notice!

2023-04-06 07:25 UTC, MarcusGrass commented on boot-strap/src/main.rs
> +    let enc_c = encrypted.clone();
Nice catch, clippy usually swoops these up!

2023-04-06 07:49 UTC, MarcusGrass commented
I'll settle for this for now, having both the salt and nonce in the header is unnecessary, but I think I'll have to rethink the header anyway. Ideally it would have a flexible length so that the header could be parsed in a backwards compatible way if stuff changes in it. I was thinking about duplicating the header as a footer to prevent bit-rot making the kernel unbootable, then again maybe that's not the biggest issue when it's just a single file that can fairly easily be rebuilt.  

Ideally I'll figure out a way not to include any configuration into to the bootloader binary, but for that I have to find a way to navigate the vfat filesystem on the UEFI-level, if I can do that, the build step would be a lot simpler, initially, an initramfs.cfg could be generated, then any time you change the kernel you just run `boot-strap` without needing to recompile the bootloader, that way it could more easily go into a mkinitcpio or whatever else.

Funnily, the project structure is messy because it started as just an initramfs in Rust, then I started looking at the bootloader, then merged the projects, so it's a bit strange overall.

It probably should be separate things, but it's difficult to separate if encryption is present, at least without looking at decrypting a luks partition. That might not necessarily be so hard, but I haven't looked into it yet. It has to be done at the UEFI-level, which is always a bit of a hassle. 

I think the main improvements that would make this usable is to figure out if I can find `cwd` in UEFI, if I can do that we don't need any data inserted into the bootloader binary. Secondly, figuring out how to pass kernel parameters when starting the UEFI-image is important to be able to support an initramfs that's not compiled into the kernel. 

But as always, first make it work, then make it good. I think having correct encryption is prio 1, thank you a lot for the help with that!

2023-04-06 08:05 UTC, merged